from voluptuous import Schema, ALLOW_EXTRA


class User:
    user_schema = Schema({'Id': int,
                          'Email': str,
                          'FirstName': str,
                          'IsActive': bool,
                          'IsAuthorized': bool,
                          'IsOnline': bool,
                          'LastName': str,
                          'MobilePhone': str,
                          'Password': str,
                          'Contract': str,
                          'IconUrl': str,
                          'IsImported': bool,
                          'ExternalUserServiceId': int,
                          'ExternalCode': str,
                          'CreatedAt': str,
                          'UpdatedAt': str,
                          'CashbackPercent': int,
                          'Point': int,
                          'Snowflakes': int,
                          'CreditLimit': int,
                          'CreditAvailable': bool,
                          'CityId': int,
                          'MentorId': int,
                          'MentorContract': str,
                          'IsSubscribeNewsletter': bool,
                          'RegistrationDomain': str,
                          'IconId': int,
                          'Gender': str,
                          'Birthday': str,
                          'FamilyName': str,
                          'Bonus': int,
                          'CurrencyId': int,
                          'RankId': int,
                          'IsBirthdayChanged': bool,
                          'ClientServiceCenterId': int,
                          'IsEmailVerified': bool,
                          'IsPhoneVerified': bool,
                          'RegisteredAt': str,
                          'IsFamily': bool,
                          'LanguageId': int,
                          'OraEmployeeId': int,
                          'Hash': str,
                          'UserTypeId': int,
                          'IsRegNeedToPay': bool}, extra=ALLOW_EXTRA)

    auth_user_schema = Schema({'Model': {'Id': int,
                                         'Email': str,
                                         'Password': str,
                                         'Contract': str,
                                         'Token': str,
                                         'UserId': int,
                                         'User': user_schema,
                                         'IsActive': bool,
                                         'Phone': str,
                                         'CityId': int,
                                         'Longitude': str,
                                         'Latitude': str,
                                         'OraEmployeeId': int}}, extra=ALLOW_EXTRA)
